// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSUwkcpth4vlaIZZX0LeeGg5pcLebIL9I',
    appId: '1:950880620199:web:5ae1c0551eb1c8064e1582',
    messagingSenderId: '950880620199',
    projectId: 'celestial-agri-iot',
    authDomain: 'celestial-agri-iot.firebaseapp.com',
    storageBucket: 'celestial-agri-iot.firebasestorage.app',
    measurementId: 'G-PZCSYYT1BN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOzSXzkGZEaAbhlFcXJJ7h5DqHnb4hkI8',
    appId: '1:950880620199:android:ee1b7961f0bbe90d4e1582',
    messagingSenderId: '950880620199',
    projectId: 'celestial-agri-iot',
    storageBucket: 'celestial-agri-iot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJBE_wXb-cuGwhpiu7-8eGdMaI87m4CoE',
    appId: '1:950880620199:ios:fd23b17c4964a9e44e1582',
    messagingSenderId: '950880620199',
    projectId: 'celestial-agri-iot',
    storageBucket: 'celestial-agri-iot.firebasestorage.app',
    iosBundleId: 'com.example.flutterproj1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJBE_wXb-cuGwhpiu7-8eGdMaI87m4CoE',
    appId: '1:950880620199:ios:fd23b17c4964a9e44e1582',
    messagingSenderId: '950880620199',
    projectId: 'celestial-agri-iot',
    storageBucket: 'celestial-agri-iot.firebasestorage.app',
    iosBundleId: 'com.example.flutterproj1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSUwkcpth4vlaIZZX0LeeGg5pcLebIL9I',
    appId: '1:950880620199:web:cab26c185beb89704e1582',
    messagingSenderId: '950880620199',
    projectId: 'celestial-agri-iot',
    authDomain: 'celestial-agri-iot.firebaseapp.com',
    storageBucket: 'celestial-agri-iot.firebasestorage.app',
    measurementId: 'G-60G2HM5DRW',
  );
}
